TEST_LONG = 1
TEST_MULTI = 1
TEST_RM_SIPI = 1
TEST_PM_SIPI = 1
TEST_LM_SIPI = 1
TEST_VMX = 2

STATIC_PAGE32 =	0
STATIC_PAGE64 = 0
STATIC_PAGEVM = 0

RESIDENT = 1
RESIDENT_OWN_PM_STACK = 1
RESIDENT_OWN_LM_STACK = 1